### ISSUE TITLE
stats and hud will not show up in web browsers

### ISSUE THREAD

**Issue by MarcelineBaka** [SpeedrunTooling/SRTPluginProviderRE2#13]
when I initiate srthost plugin for re2r it launches and is successful and shows in game, but when I try to have it displayed in obs or on the web it just says "IGT: undefined" and nothing else. I've tried uninstalling and reinstalling everything and deleting everything and getting the newest srthost from here.
![image](https://github.com/SpeedrunTooling/SRTPluginProviderRE2/assets/137375476/bd586832-7132-4511-b784-637fa1e6cb72)

**Comment by VideoGameRoulette** [comment]
not an actual issue you are using old website which i've dropped support for, there is a new website to keep old one up for legacy plugins, [New Website](https://srt.videogameroulette.ca/widgets/RE2R/json)

**Comment by MarcelineBaka** [comment]
Thanks for the response. So JSON will show my health and DA but won’t
display the enemies or bosses health. Also the inventory works. When I goto the websocket and I put in my token, it just says "200 Connected to Game Awaiting session event to start..." but nothing happens.

**Comment by VideoGameRoulette** [comment]
right click to reveil more options to customize your UI layout
