### ISSUE TITLE
Unknow version (Build ID = 11636119)

### ISSUE THREAD

**Issue by KnifeOnlyI** [SpeedrunTooling/SRTPluginProviderRE2#18]
I'll try to use SRTPluginManager with "Resident Evil 2 Remake (2.0.2.0)" plugin. Unfortunatly it seems my game version isn't supported by the tool.

According to this screenshot I use build ID [11636119](https://steamdb.info/patchnotes/11636119/) : 

![image](https://github.com/SpeedrunTooling/SRTPluginProviderRE2/assets/28624619/1a49692c-fc3c-4bb1-a8be-1124c72ecd8c)

In version.log I have this : 

```
private static readonly byte[] re2??_00000000 = new byte[32] { 0x6C, 0xAA, 0xA8, 0x15, 0xBF, 0x9E, 0x95, 0xF8, 0xA8, 0x41, 0xBC, 0x81, 0xFD, 0xF2, 0x9F, 0xEC, 0x55, 0xE8, 0x36, 0xC8, 0x7B, 0xAB, 0x8A, 0x76, 0xD5, 0x5C, 0x69, 0xBE, 0xF9, 0xAD, 0xA9, 0x41 };
```

I made a [pull request](https://github.com/SpeedrunTooling/SRTPluginProviderRE2/pull/19) to add a support to this version (additionnaly the old one).

**Comment by Squirrelies** [comment]
Merged, thanks!
